name: ProperNametags
version: '${project.version}'
main: be.esmay.propernametags.ProperNametags
api-version: '1.20'
depend:
  - packetevents
softdepend:
  - TAB
  - PlaceholderAPI
commands:
  propernametags: